print("what is your name?")
name = input()
print("Hello " + name + ", welcome to the world of Python programming!")    
print("How old are you?")
age = input()
print("You are " + age + " years old.")
print("What is your favorite color?")
color = input()
print("Your favorite color is " + color + ".")
